/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-09-27 06:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/study/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gofarm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1569465106201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Quite Light</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:400,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("<link href=\"main/plugin-frameworks/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/plugin-frameworks/swiper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/fonts/ionicons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/main_content.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".chatjoin\").click(function(){\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginOk}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"\"){\r\n");
      out.write("\t\t\t\talert(\"로그인이 필요합니다.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tconsole.log(\"로그인햇네\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-menu {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin-left: 25%;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_icon{\r\n");
      out.write("width: 50px;\r\n");
      out.write("height: 50px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#chatimg{\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/main_nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"slider-main h-800x h-sm-auto pos-relative pt-95 pb-25\">\r\n");
      out.write("\t\t<div class=\"img-bg bg-1 bg-layer-4\"></div>\r\n");
      out.write("\t\t<div class=\"container-fluid h-100 mt-xs-50\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-5 h-100 h-sm-50\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"dplay-tbl\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dplay-tbl-cell color-white mtb-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mx-w-400x\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>ART</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1 class=\"mt-20 mb-30\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b style=\"font-size: 60px; color: #5F9EA0\"> GO! FARM </b> </br> <b\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 48px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;농사꾼\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t되기</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"plr-20 btn-brdr-grey color-white\" href=\"#\"><b>Continue\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tReading</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- mx-w-200x -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- dplay-tbl-cell -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- dplay-tbl -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col-sm-6 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-sm-12 col-md-6 h-sm-50 oflow-hidden swiper-area pos-relative\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"abs-blr pos-sm-static\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row pos-relative mt-50 all-scroll\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"swiper-scrollbar resp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\" style=\"height: 250px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"mb-50 color-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>FARM STEP</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"swiper-container oflow-visible\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-slide-effect=\"slide\" data-autoheight=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-swiper-speed=\"500\" data-swiper-margin=\"25\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-swiper-slides-per-view=\"2\" data-swiper-breakpoints=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-scrollbar=\"true\" data-swiper-loop=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-swpr-responsive=\"[1, 2, 1, 2]\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- data-swiper-autoplay=\"1000\"  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/step111.png\" width=200px height=175px\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"plr-25 ptb-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"color-ash\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b class=\"plan\"><strong>정보수집</strong> </b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/step222.png\" width=200px; height=175px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"plr-25 ptb-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"color-ash\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b class=\"plan recenter\">작물선택</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/step333.png\" width=200px; height=175px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"plr-25 ptb-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"color-ash\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b class=\"plan\">기술습득</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/step444.png\" width=200px; height=175px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"plr-25 ptb-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"color-ash\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b class=\"plan\">농지구매</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/step555.png\" width=200px; height=175px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"plr-25 ptb-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"color-ash\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b class=\"plan\">계획수립</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- hot-news -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- swiper-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- swiper-container -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- col-sm-6 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- all-scroll -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col-sm-6 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- slider-main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"bg-1-white ptb-0\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-1\"></div>\r\n");
      out.write("            <div class=\"col-md-12 col-lg-8 ptb-50 pr-30 pr-md-15\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <h4 class=\"mb-30 mt-30 clearfix\">\r\n");
      out.write("                  <b>한눈에 바로보기</b>\r\n");
      out.write("               </h4>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                  <!-- START OF SECOND PARA -->\r\n");
      out.write("                  <div class=\"col-sm-12 col-md-12 col-lg-12 col-xl-8 mb-30\">\r\n");
      out.write("                     <div class=\"card h-100 h-xs-500x\">\r\n");
      out.write("                        <div class=\"sided-half sided-xs-half h-100 bg-white\">\r\n");
      out.write("\r\n");
      out.write("                           <!-- SETTING IMAGE WITH bg-2 -->\r\n");
      out.write("                           <div class=\"s-left w-50 w-xs-100 h-100 h-xs-50 pos-relative\">\r\n");
      out.write("                              <div class=\"bg-2 abs-tblr\"></div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"s-right w-50 w-xs-100 h-xs-50\">\r\n");
      out.write("                              <div class=\"plr-25 ptb-25 h-100\">\r\n");
      out.write("                                 <div class=\"dplay-tbl\">\r\n");
      out.write("                                    <div class=\"dplay-tbl-cell\">\r\n");
      out.write("\r\n");
      out.write("                                       <h5 class=\"color-ash\">\r\n");
      out.write("                                          <b>장터</b>\r\n");
      out.write("                                       </h5>\r\n");
      out.write("                                       <h2 class=\"mtb-10\">\r\n");
      out.write("                                          <a href=\"productList.do\"><b class=\"ngc\">상품 목록 보기</b><br></a>\r\n");
      out.write("                                       </h2>\r\n");
      out.write("\r\n");
      out.write("                                       <h5 class=\"color-ash\">\r\n");
      out.write("                                          <b>#필요상품 #직접 판매</b> <br>\r\n");
      out.write("                                       </h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- dplay-tbl-cell -->\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <!-- dplay-tbl -->\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- plr-25 ptb-25 -->\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <!-- s-right -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- sided-half -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- card -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- col-lg-8 col-md-12 -->\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-sm-6 col-md-6 col-lg-6 col-xl-4 mb-30\">\r\n");
      out.write("                     <div class=\"card h-100 h-xs-350x\">\r\n");
      out.write("                        <div class=\"bg-white h-100\">\r\n");
      out.write("\r\n");
      out.write("                           <!-- SETTING IMAGE WITH bg-3 -->\r\n");
      out.write("                           <div class=\"h-50 bg-3 dplay-lg-none dplay-xs-block\"></div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"plr-25 ptb-15 h-50\">\r\n");
      out.write("                              <div class=\"dplay-tbl\">\r\n");
      out.write("                                 <div class=\"dplay-tbl-cell\">\r\n");
      out.write("\r\n");
      out.write("                                    <h5 class=\"color-ash\">\r\n");
      out.write("                                       <b>게시판</b>\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    <h4 class=\"mtb-10\">\r\n");
      out.write("                                       <a href=\"board.do\"><b>커뮤니티 바로보기 </b><br></a>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <!-- dplay-tbl-cell -->\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- dplay-tbl -->\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <!-- plr-25 ptb-15 -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- hot-news -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- card -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- col-lg-4 col-md-6 -->\r\n");
      out.write("                  <!-- END OF SECOND PARA -->\r\n");
      out.write("                  <div class=\"col-sm-6 col-md-6 col-lg-6 col-xl-4 mb-30\">\r\n");
      out.write("                     <!-- START OF THIRD PARA -->\r\n");
      out.write("                     <div class=\"card pos-relative h-100 color-black\">\r\n");
      out.write("                        <div class=\"plr-25 ptb-15 h-100\">\r\n");
      out.write("                           <h5 class=\"color-ash\">\r\n");
      out.write("                              <b>구인/구직</b>\r\n");
      out.write("                           </h5>\r\n");
      out.write("                           <h4 class=\"mtb-10\">\r\n");
      out.write("                              <a href=\"recruit2.do\"><b>구인/구직 정보 보기</b></a>\r\n");
      out.write("                              <img src=\"main/images/eyes.png\" style=\"width:20%; height:100%\"/>\r\n");
      out.write("                           </h4>\r\n");
      out.write("                           \r\n");
      out.write("                           <!-- dplay-tbl-cell -->\r\n");
      out.write("                           <!-- dplay-tbl -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- plr-25 ptb-15 -->\r\n");
      out.write("                        <!-- card -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- col-lg-4 col-md-6 -->\r\n");
      out.write("                  <div class=\"col-sm-6 col-md-6 col-lg-6 col-xl-4 mb-30\">\r\n");
      out.write("                     <!-- SETTING IMAGE WITH bg-4 -->\r\n");
      out.write("                     <div class=\"card pos-relative h-100 color-black \">\r\n");
      out.write("                        <div class=\"plr-25 ptb-15\">\r\n");
      out.write("                           <h5 class=\"color-grey\">\r\n");
      out.write("                              <b class=\"h\">구인</b>\r\n");
      out.write("                           </h5>\r\n");
      out.write("                           <h4 class=\"mtb-10\">\r\n");
      out.write("                              <a href=\"auctionList.do\"><b>경매 바로 가기</b></a>\r\n");
      out.write("                              <img src=\"main/images/money.png\" style=\"width:20%; height:100%\"/>\r\n");
      out.write("                           </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- hot-news -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- card -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- col-lg-4 col-md-6 -->\r\n");
      out.write("                  <div class=\"col-sm-6 col-md-6 col-lg-6 col-xl-4 mb-30\">\r\n");
      out.write("                     <!-- SETTING IMAGE WITH bg-5 -->\r\n");
      out.write("                     <div class=\"card pos-relative h-100\">\r\n");
      out.write("                        <div class=\"plr-25 ptb-15\">\r\n");
      out.write("                           <h5 class=\"color-grey\">\r\n");
      out.write("                              <b>게시판</b>\r\n");
      out.write("                           </h5>\r\n");
      out.write("                           <h4 class=\"mtb-10\">\r\n");
      out.write("                              <a href=\"chatlist.do\"><b>오픈채팅방 바로가기</b></a>\r\n");
      out.write("                              <img src=\"main/images/airplane.png\" style=\"width:20%; height:100%\"/>\r\n");
      out.write("                           </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- hot-news -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- card -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- col-lg-4 col-md-6 -->\r\n");
      out.write("                  <!-- END OF THIRD PARA -->\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 class=\"mb-30 mt-20 clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<b>귀농 정보 동영상</b>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12 mb-30 swiper-area \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- SETTING IMAGE WITH bg-6 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"bg-6 p-40 bg-layer-4 pos-relative z-1 oflow-hidden pr-0 color-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mx-w-600x\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> <b>귀농에 대한 <br>자세한 내용은 <br>상단바 <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"color: #00CED1\">INFO</i> 를 이용해주세요\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- mx-w-200x -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"all-scroll pos-relative \" style=\"height: 500px; margin-top: 150px\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"mb-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>MORE VIDEO</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"swiper-scrollbar\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"swiper-container oflow-visible\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-slide-effect=\"slide\" data-autoheight=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-swiper-speed=\"500\" data-swiper-margin=\"25\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-swiper-slides-per-view=\"3\" data-swiper-breakpoints=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-scrollbar=\"true\" data-swiper-loop=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-swpr-responsive=\"[1, 2, 2, 2]\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 동영상 슬라이드  시작 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pos-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mt-4 embed-responsive embed-responsive-16by9\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/Ltad3MBSNao\"></iframe> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- pos-relative -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pos-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mt-4 embed-responsive embed-responsive-16by9\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/GAyQMj9IGlk\"></iframe> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- pos-relative -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pos-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mt-4 embed-responsive embed-responsive-16by9\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/XgPtIgyrn_k\"></iframe> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- pos-relative -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"swiper-slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pos-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mt-4 embed-responsive embed-responsive-16by9\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/ON3ih_iBhu8\"></iframe> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- pos-relative -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- swiper-slide -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- swiper-wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- swiper-container -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- swiper-area -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- bg-4 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- col-lg-4 col-md-6 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col-sm-9 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 col-lg-3 bg-2-white ptb-50 pl-30 pl-md-15\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mx-w-md-400x mlr-md-auto\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mb-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"mb-30 mt-30 clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b class=\"blink\">실시간 채팅방</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"main/images/up.png\" style=\"width:15%; height:100%\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- sided-80x -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"mb-50 pos-relative dplay-block\" href=\"http://www.returnfarm.com/\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"main/images/link_img.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"abs-tblr z-10 \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"dplay-tbl text-center color-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dplay-tbl-cell\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- dplay-tbl -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <!-- abs-tblr -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- mb-50 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"mb-30 mt-30 clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b class=\"blink\">실시간 인기상품</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- s-left -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- sided-80x -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- sided-80x -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- mb-50 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- mx-w-400 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- col-sm-9 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col-sm-3 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- row -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer 시작-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- footer 끝 -->\r\n");
      out.write("\t<!-- SCIPTS -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/swiper.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/common/scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/main/index.jsp(490,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/main/index.jsp(490,7) '${cList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/main/index.jsp(490,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cdto");
      // /WEB-INF/view/main/index.jsp(490,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /WEB-INF/view/main/index.jsp(490,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(4);
      // /WEB-INF/view/main/index.jsp(490,7) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"sided-80x mb-20\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"s-left color-ash text-center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dplay-tbl\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"dplay-tbl-cell\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"/gofarm/profileUpload/chatimg.png\" src=\"/gofarm/profileUpload/chatimg.png\" id=\"chatimg\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- dplay-tbl-cell -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- dplay-tbl -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<!-- s-left -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"s-right\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"pt-5\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chatList }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" class=\"chatjoin\"><b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdto.ct_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\t</b></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<!-- s-left -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- sided-80x -->\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/main/index.jsp(491,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("chatjoin.do");
      // /WEB-INF/view/main/index.jsp(491,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("chatList");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          _jspx_push_body_count_c_005fforEach_005f0[0]++;
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005furl_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
          _jspx_push_body_count_c_005fforEach_005f0[0]--;
        }
      }
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
      // /WEB-INF/view/main/index.jsp(492,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("chatcode");
      // /WEB-INF/view/main/index.jsp(492,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdto.chatcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/main/index.jsp(537,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/main/index.jsp(537,7) '${pList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/main/index.jsp(537,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/view/main/index.jsp(537,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(3);
      // /WEB-INF/view/main/index.jsp(537,7) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setStep(1);
      // /WEB-INF/view/main/index.jsp(537,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("cdto");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"sided-80x mb-20\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"s-left\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/gofarm/profileUpload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdto.pd_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<!-- s-left -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"s-right\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<h5>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdto.pd_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<!-- s-left -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/view/main/index.jsp(538,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("productView.do");
      // /WEB-INF/view/main/index.jsp(538,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("product");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          _jspx_push_body_count_c_005fforEach_005f1[0]++;
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f1);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005furl_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f2(_jspx_th_c_005furl_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005furl_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
          _jspx_push_body_count_c_005fforEach_005f1[0]--;
        }
      }
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f1_reused = false;
    try {
      _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f1);
      // /WEB-INF/view/main/index.jsp(539,9) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setName("currentPage");
      // /WEB-INF/view/main/index.jsp(539,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setValue("1");
      int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
      if (_jspx_th_c_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
      _jspx_th_c_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f2_reused = false;
    try {
      _jspx_th_c_005fparam_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f1);
      // /WEB-INF/view/main/index.jsp(540,9) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setName("prod_code");
      // /WEB-INF/view/main/index.jsp(540,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cdto.prod_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f2 = _jspx_th_c_005fparam_005f2.doStartTag();
      if (_jspx_th_c_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
      _jspx_th_c_005fparam_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f2_reused);
    }
    return false;
  }
}
