/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-09-27 06:43:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Font -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:400,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("<link href=\"main/plugin-frameworks/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/plugin-frameworks/swiper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/fonts/ionicons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/main_content.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"user/css/login.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t//console.log(1);\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"fail\"){\r\n");
      out.write("\t\t alert(\"로그인 실패했습니다 다시 입력하세요\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".kakao\").click(function(){\r\n");
      out.write("\t\tconsole.log(\"카카오로그인 클릭\");\r\n");
      out.write("\t\twindow.location.href=\"kakaologin.do\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".naver\").click(function(){\r\n");
      out.write("\t\tconsole.log(\"네이버로그인 클릭\");\r\n");
      out.write("\t\twindow.location.href=\"naverlogin.do\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#join\").click(function(){\r\n");
      out.write("\t\tconsole.log(\"join\")\r\n");
      out.write("\t\twindow.location.href = \"signup.do\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/main_nav.jsp", out, false);
      out.write("\r\n");
      out.write("<br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"login-box\">\r\n");
      out.write(" <form action=\"loginpro.do\" method=\"post\">\r\n");
      out.write("  <div class=\"left\">\r\n");
      out.write("    <h2>로그인</h2>\r\n");
      out.write("   <br/>\r\n");
      out.write("   <br/>\r\n");
      out.write("   \r\n");
      out.write("    <input type=\"text\" name=\"userid\" placeholder=\"ID\" required=\"required\"/>\r\n");
      out.write("    <input type=\"password\" name=\"userpw\" placeholder=\"PASSWORD\" required=\"required\"/>\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <input type=\"submit\" name=\"signup_submit\" value=\"로그인\" />\r\n");
      out.write("    <input type=\"submit\" name=\"signup_submit\" id=\"join\" value=\"회원가입\" />\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  <div class=\"right\">\r\n");
      out.write("    <span class=\"loginwith\">소셜 로그인</span> \r\n");
      out.write("    \r\n");
      out.write("    <button class=\"social-signin naver\">네이버 로그인</button>\r\n");
      out.write("    <button class=\"social-signin kakao\">카카오 로그인</button>\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"or\">OR</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br><br><br><br>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"main/plugin-frameworks/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"main/plugin-frameworks/swiper.js\"></script>\r\n");
      out.write("<script src=\"main/common/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
