/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-09-27 06:46:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"board/index/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- 메인 네비바에 이거4개만 들어가면 됨 -->\r\n");
      out.write("<link href=\"main/plugin-frameworks/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/fonts/ionicons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"main/common/main_nav.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 메인 네비바 링크 끝 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!----webfonts---->\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!----//webfonts---->\r\n");
      out.write("<!-- Global CSS for the page and tiles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"board/index/css/main.css\">\r\n");
      out.write("<!-- //Global CSS for the page and tiles -->\r\n");
      out.write("<!---start-click-drop-down-menu----->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #A2BBCA;\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/main_nav.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!---start-content---->\r\n");
      out.write("\t<div class=\"content\" style=\"margin-top: 185px; margin-bottom: 150px\">\r\n");
      out.write("\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t<div id=\"main\" role=\"main\">\r\n");
      out.write("\t\t\t\t<ul id=\"tiles\">\r\n");
      out.write("\t\t\t\t\t<!-- These are our grid blocks -->\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='board_job.do';\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/index/images/img1.jpg\" width=\"282\" height=\"118\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"post-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_job.do\">A. 구인 구직</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><a href=\"board_job.do\"><label> </label> Job </a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>구인과 구직에 관련된 정보로 소통하세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Communicate with information on job openings and job\r\n");
      out.write("\t\t\t\t\t\t\t\t\topenings.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-info-rate-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rateit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"post-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='board_trade.do';\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/index/images/img2.jpg\" width=\"282\" height=\"344\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"post-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_trade.do\">B. 판매 경매</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><a href=\"board_trade.do\"><label></label>Shop</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>판매에 관련된 정보를 얻어가세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Get sales information.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-info-rate-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rateit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"post-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='board_shard.do';\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/index/images/img3.jpg\" width=\"282\" height=\"210\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"post-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_shard.do\">C. 나눔</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><a href=\"board_shard.do\"><label> </label>Share</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>다양한 상품을 나눔하세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Share a variety of products</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-info-rate-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rateit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"post-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='board_talk.do';\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/index/images/img4.jpg\" width=\"282\" height=\"385\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"post-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_talk.do\">D. 사담</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><a href=\"board_talk.do\"><label> </label>Talk</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>사람들과 즐겁게 소통하세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Commumicate joyfull with people.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-info-rate-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rateit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"post-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='notice.do';\"><img src=\"board/index/images/laf.jpg\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"282\" height=\"210\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"post-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice.do\">F. 공지 </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span><a href=\"notice.do\"><label></label>Notice</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>유익한 공지사항을 확인해보세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Check out the many announcements</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-info-rate-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rateit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"post-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!----//--->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- End of grid blocks -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!---//End-content---->\r\n");
      out.write("\t<!----wookmark-scripts---->\r\n");
      out.write("\t<script src=\"board/index/js/jquery.imagesloaded.js\"></script>\r\n");
      out.write("\t<script src=\"board/index/js/jquery.wookmark.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("      (function($) {\r\n");
      out.write("         var $tiles = $('#tiles'), $handler = $('li', $tiles), $main = $('#main'), $window = $(window), $document = $(document), options = {\r\n");
      out.write("            autoResize : true, // This will auto-update the layout when the browser window is resized.\r\n");
      out.write("            container : $main, // Optional, used for some extra CSS styling\r\n");
      out.write("            offset : 20, // Optional, the distance between grid items\r\n");
      out.write("            itemWidth : 280\r\n");
      out.write("         // Optional, the width of a grid item\r\n");
      out.write("         };\r\n");
      out.write("         /**\r\n");
      out.write("          * Reinitializes the wookmark handler after all images have loaded\r\n");
      out.write("          */\r\n");
      out.write("         function applyLayout() {\r\n");
      out.write("            $tiles.imagesLoaded(function() {\r\n");
      out.write("               // Destroy the old handler\r\n");
      out.write("               if ($handler.wookmarkInstance) {\r\n");
      out.write("                  $handler.wookmarkInstance.clear();\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("               // Create a new layout handler.\r\n");
      out.write("               $handler = $('li', $tiles);\r\n");
      out.write("               $handler.wookmark(options);\r\n");
      out.write("            });\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         // Call the layout function for the first time\r\n");
      out.write("         applyLayout();\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      })(jQuery);\r\n");
      out.write("   </script>\r\n");
      out.write("\t<!----//wookmark-scripts---->\r\n");
      out.write("\t<!----start-footer--->\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- SCIPTS -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/plugin-frameworks/swiper.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"main/common/scripts.js\"></script>\r\n");
      out.write("\t<!----//End-footer--->\r\n");
      out.write("\t<!---//End-wrap---->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
